### ISSUE TITLE
Release new version of mysql-dist

### ISSUE THREAD

**Issue by longtimeago** [jcabi/jcabi-mysql-maven-plugin#43]
We need to release new version of mysql-dist with mysql 5.6.21 of higher.
Issue https://github.com/jcabi/jcabi-mysql-maven-plugin/issues/39 should be fixed in that version.

**Comment by shrutiujjwal** [comment]
Is there any plans to support the latest version of MySQL? like: 5.7.16 -- need this urgently for an In Memory support of JSON with MySQL. Any help/inputs will be appreciated. TIA.
