### ISSUE TITLE
broken link in README.md

### ISSUE THREAD

**Issue by apocarteres** [jcabi/jcabi-mysql-maven-plugin#60]
link mentioned in README.md 
<pre>
http://www.yegor256.com/2014/05/21/mysql-maven-plugin.html
</pre>
doesn't work

**Comment by yegor256** [comment]
opens for me: http://www.yegor256.com/2014/05/21/mysql-maven-plugin.html

**Comment by apocarteres** [comment]
yes, it works now for me too
