### ISSUE TITLE
build failed on Travis

### ISSUE THREAD

**Issue by apocarteres** [jcabi/jcabi-mysql-maven-plugin#63]
one of builds on Travis is failed. Looks like a bug somewhere

<pre>
out of java.lang.ProcessBuilder#start[1047] in 56ms
Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 0.453 sec <<< FAILURE! - in com.jcabi.mysql.maven.plugin.InstancesTest
willCreateDatabaseEvenWithoutClear(com.jcabi.mysql.maven.plugin.InstancesTest)  Time elapsed: 0.062 sec  <<< ERROR!
java.io.IOException: Cannot run program "/home/travis/build/jcabi/jcabi-mysql-maven-plugin/target/mysql-dist/bin/mysqld" (in directory "/home/travis/build/jcabi/jcabi-mysql-maven-plugin/target/mysql-dist"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at com.jcabi.mysql.maven.plugin.Instances.process(Instances.java:213)
	at com.jcabi.mysql.maven.plugin.Instances.start_aroundBody0(Instances.java:130)
	at com.jcabi.mysql.maven.plugin.Instances$AjcClosure1.run(Instances.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.mysql.maven.plugin.Instances.start(Instances.java:123)
	at com.jcabi.mysql.maven.plugin.InstancesTest.willCreateDatabaseEvenWithoutClear(InstancesTest.java:361)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
</pre>

It happens from time to time
Now it blocks https://github.com/jcabi/jcabi-mysql-maven-plugin/issues/58
full log: https://travis-ci.org/jcabi/jcabi-mysql-maven-plugin/builds/49018546

**Comment by dmarkov** [comment]
I'll find a developer for the task soon...

**Comment by dmarkov** [comment]
@apocarteres many thanks for the bug report, I added 15 mins to your acc, transaction `51288004`

**Comment by dmarkov** [comment]
@tousifkhan could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by dmarkov** [comment]
@tousifkhan check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... -30 to your rating, your total score is [-240](http://www.netbout.com/b/35305?open=rating)

**Comment by dmarkov** [comment]
@ikhvostenkov this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmarkov** [comment]
@ikhvostenkov you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck)... -30 added to your rating, at the moment it is: [-105](http://www.netbout.com/b/35232?open=rating)

**Comment by dmarkov** [comment]
@ikhvostenkov this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -60 to your rating, your total score is [-210](http://www.netbout.com/b/35232?open=rating)

**Comment by yegor256** [comment]
@dmarkov I confirm that this bug is still here, I can reproduce it locally, sometimes

**Comment by dmarkov** [comment]
@jrdalpra please help, the task is yours

**Comment by jrdalpra** [comment]
@yegor256 it always happens on Windows. You can see at appvevor build.

**Comment by jrdalpra** [comment]
@dmarkov @yegor256 The PR #80 correct this problem. Can you review, please? Thanks.

**Comment by dmarkov** [comment]
@jrdalpra you're holding this task for 16 days already. -30 added to your rating, at the moment it is: [+278](http://www.netbout.com/b/36044?open=rating)

**Comment by jrdalpra** [comment]
@dmarkov There's a Pr ready for review. Can you reconsider this?

On Monday, February 8, 2016, Dan Markov <notifications@github.com> wrote:

> @jrdalpra <https://github.com/jrdalpra> you're holding this task for 16
> days already. -30 added to your rating, at the moment it is: +278
> <http://www.netbout.com/b/36044?open=rating>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jcabi/jcabi-mysql-maven-plugin/issues/63#issuecomment-181237903>
> .
>


-- 
José Volmei Dal Prá Junior - (49) 9112 9359
Bacharel em Ciência da Computação - UnoChapecó
Pós-Graduado em Desenvolvimento de Software Com Java - Unoesc Xxe
Consultor Java e TotalCross
https://github.com/jrdalpra
http://www.kombo.com.br/meucurriculo/jrdalpra
http://www.linkedin.com/in/jrdalpra
msn: jr_dalpra@hotmail.com
skype: jrdalpra
e-mail: jrdalpra@gmail.com

**Comment by dmarkov** [comment]
> @dmarkov There's a Pr ready for review. Can you reconsider this?
> 
> On Monday, February 8, 2016, Dan Markov <notifications@github.com> wrote:
> 
> > @jrdalpra <https://github.com/jrdalpra> you're holding this task for 16
> > days already. -30 added to your rating, at the moment it is: +278
> > <http://www.netbout.com/b/36044?open=rating>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jcabi/jcabi-mysql-maven-plugin/issues/63#issuecomment-181237903>
> > .
> >
> 
> 
> -- 
> José Volmei Dal Prá Junior - (49) 9112 9359
> Bacharel em Ciência da Computação - UnoChapecó
> Pós-Graduado em Desenvolvimento de Software Com Java - Unoesc Xxe
> Consultor Java e TotalCross
> https://github.com/jrdalpra
> http://www.kombo.com.br/meucurriculo/jrdalpra
> http://www.linkedin.com/in/jrdalpra
> msn: jr_dalpra@hotmail.com
> skype: jrdalpra
> e-mail: jrdalpra@gmail.com
> 

@jrdalpra sure thanks

**Comment by jrdalpra** [comment]
@dmarkov can you update the comment and remove my e-mail signature, please?

**Comment by jrdalpra** [comment]
@dmarkov can you give my point back. :)

**Comment by dmarkov** [comment]
> @dmarkov can you update the comment and remove my e-mail signature, please?

@jrdalpra done

**Comment by dmarkov** [comment]
> @dmarkov can you give my points back. :)

@jrdalpra delay is a delay, no points back

**Comment by jrdalpra** [comment]
@dmarkov no problem. But If I complete it I'll get point and be paid?

**Comment by dmarkov** [comment]
> @dmarkov no problem. But If I complete it I'll get point and be paid?

@jrdalpra yes, sure, the task is yours now

**Comment by dmarkov** [comment]
@jrdalpra the task is not yours any more, please stop... -60 to your rating, your total score is [+218](http://www.netbout.com/b/36044?open=rating)

**Comment by jrdalpra** [comment]
@dmarkov I don't understand. You said that the task is mine. There´s a PR #80 waiting for review. What´s the problem? I don´t know how to proceed.

**Comment by jrdalpra** [comment]
@dmarkov can you assign this to me again? I have a PR #80 waiting for review. There's no reason to assign to another developer. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov I don't understand. You said that the task is mine. There´s a PR #80 waiting for review. What´s the problem? I don´t know how to proceed.

@jrdalpra check this: http://at.teamed.io/policy.html#7 and this: http://at.teamed.io/policy.html#16

**Comment by jrdalpra** [comment]
@dmarkov fine. I'll finish the task anyway. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov fine. I'll finish the task anyway. Thanks.

@jrdalpra sure, no problem

**Comment by dmarkov** [comment]
@amihaiemil please go ahead with this task, it's yours

**Comment by amihaiemil** [comment]
@dmarkov cc: @yegor256  Can you assign this back to @jrdalpra ? It makes no sense to start over again if there's PR #80 waiting to be merged...

**Comment by jrdalpra** [comment]
@dmarkov @yegor256 can you merge my PR #80?

**Comment by yegor256** [comment]
@dmarkov assign to @jrdalpra please

**Comment by yegor256** [comment]
@jrdalpra keep in mind that addressing one message to multiple recipients is a bad practice. in the end, nobody will answer you because everyone will think that the other person will do it. always address your message to only one person. if that person doesn't reply, post another message to another person. but never broadcast.

**Comment by dmarkov** [comment]
> @dmarkov assign to @jrdalpra please

@yegor256 done! @jrdalpra the task is yours, please proceed

**Comment by jrdalpra** [comment]
@dmarkov thanks

**Comment by jrdalpra** [comment]
@yegor256 sorry. Got it.

**Comment by jrdalpra** [comment]
@dmarkov the PR #80 is being reviewed already.

**Comment by dmarkov** [comment]
> @dmarkov thanks

@jrdalpra sure, no problem

**Comment by dmarkov** [comment]
> @dmarkov the PR #80 is being reviewed already.

@jrdalpra thank you!

**Comment by jrdalpra** [comment]
@dmarkov the PR #80 was merged.

**Comment by dmarkov** [comment]
> @dmarkov the PR #80 was merged.

@jrdalpra thanks

**Comment by dmarkov** [comment]
@jrdalpra you're working with this issue for 16 days already. -30 added to your rating, current score is: [+218](http://www.netbout.com/b/36044?open=rating)

**Comment by jrdalpra** [comment]
@dmarkov I finished the task and I also had warned you about it. Why do I lost points if I completed the task?

**Comment by dmarkov** [comment]
> @dmarkov I finished the task and I also had warned you about it. Why do I lost points if I completed the task?

@jrdalpra the ticket is still open. why do you think that you completed the task?

**Comment by dmarkov** [comment]
@jrdalpra you were holding this task for too long, it's not yours any more, please stop. -60 added to your rating, at the moment it is: [+158](http://www.netbout.com/b/36044?open=rating)

**Comment by jrdalpra** [comment]
@apocarteres please close the ticket. thanks.

**Comment by jrdalpra** [comment]
@dmarkov sometimes you need to be more flexible. The task was done, but only the ticket at github needed to be closed. Just a little flexibility would be good. Thanks.

**Comment by apocarteres** [comment]
can't check it now. closing it since it's probably not relevant anymore. Please raise a new issue if still doesn't work.
