### ISSUE TITLE
The socket file path is too long

### ISSUE THREAD

**Issue by h4ck3rm1k3** [jcabi/jcabi-mysql-maven-plugin#81]
[INFO] [INFO] >> 160221 19:53:22 [ERROR] The socket file path is too long (> 107): /mnt/newdrive2/home/mdupont/experiments/jcabi-mysql-maven-plugin/target/it/parallel/target/mysql-data-first/mysql.sock
[INFO] [INFO] >> 160221 19:53:22 [ERROR] Aborting

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@h4ck3rm1k3 it's a duplicate of https://github.com/jcabi/jcabi-mysql-maven-plugin/issues/50
