### ISSUE TITLE
Is it possible to execute a SQL file once the mysql started?

### ISSUE THREAD

**Issue by MHL3060** [jcabi/jcabi-mysql-maven-plugin#86]
First of all, Thanks for the great maven-plugin. I have one question. is it possible to execute a SQL file once the mysql started? the reason is I need to integrate with the liquibase-maven-plugin. our liquibase changelog doesn't include the create database/schema procedure. It would be nice if this plugin can support this. Thanks.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by MHL3060** [comment]
Never mind. It is already supported by using the dbname tag

**Comment by 0crat** [comment]
Oops! Job `gh:jcabi/jcabi-mysql-maven-plugin#86` was not in scope
