### ISSUE TITLE
Need MySQL 5.7.20 package for JCABI 

### ISSUE THREAD

**Issue by QubitPi** [jcabi/jcabi-mysql-maven-plugin#90]
We successfully tested our downstream project against a manually installed MySQL at 5.7.20, but failed with jcabi whose MySQL version is at 5.6.14.

It would be fantastic if 5.7.20 could be provided in jcabi.

Thanks!

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue
